insert into cat_producto (nombre, descripcion, estado) values ('Garbage Bags - Clear', 'Open-source zero tolerance focus group', true);
insert into cat_producto (nombre, descripcion, estado) values ('Sauce - Salsa', 'Expanded hybrid toolset', true);
insert into cat_producto (nombre, descripcion, estado) values ('Oneshot Automatic Soap System', 'Ergonomic coherent protocol', false);
insert into cat_producto (nombre, descripcion, estado) values ('Cheese - Swiss Sliced', 'Sharable homogeneous ability', false);
insert into cat_producto (nombre, descripcion, estado) values ('Sprouts - Onion', 'Re-contextualized actuating software', false);
insert into cat_producto (nombre, descripcion, estado) values ('Lemonade - Mandarin, 591 Ml', 'Vision-oriented tangible model', false);
insert into cat_producto (nombre, descripcion, estado) values ('Wine - Red, Wolf Blass, Yellow', 'Streamlined neutral utilisation', true);
insert into cat_producto (nombre, descripcion, estado) values ('Shiro Miso', 'Intuitive eco-centric throughput', false);
insert into cat_producto (nombre, descripcion, estado) values ('Plasticspoonblack', 'Managed intermediate challenge', true);
insert into cat_producto (nombre, descripcion, estado) values ('Olives - Kalamata', 'Multi-lateral optimal hierarchy', false);
insert into cat_producto (nombre, descripcion, estado) values ('Bouq All Italian - Primerba', 'Mandatory non-volatile project', true);
insert into cat_producto (nombre, descripcion, estado) values ('Nantucket Apple Juice', 'Programmable global circuit', false);
insert into cat_producto (nombre, descripcion, estado) values ('Sobe - Cranberry Grapefruit', 'Customizable asynchronous toolset', false);
insert into cat_producto (nombre, descripcion, estado) values ('Puff Pastry - Slab', 'Robust content-based parallelism', true);
insert into cat_producto (nombre, descripcion, estado) values ('Pate Pans Yellow', 'User-friendly demand-driven groupware', true);
insert into cat_producto (nombre, descripcion, estado) values ('Doilies - 8, Paper', 'Horizontal encompassing focus group', false);
insert into cat_producto (nombre, descripcion, estado) values ('Quail - Whole, Boneless', 'Cloned optimizing attitude', false);
insert into cat_producto (nombre, descripcion, estado) values ('Sugar - Invert', 'Automated grid-enabled open architecture', false);
insert into cat_producto (nombre, descripcion, estado) values ('Melon - Honey Dew', 'Configurable high-level algorithm', true);
insert into cat_producto (nombre, descripcion, estado) values ('Pepper - Red Thai', 'Universal clear-thinking matrix', false);
insert into cat_producto (nombre, descripcion, estado) values ('Crab - Dungeness, Whole, live', 'Implemented zero defect info-mediaries', false);
insert into cat_producto (nombre, descripcion, estado) values ('Pork - Backs - Boneless', 'Ergonomic secondary task-force', true);
insert into cat_producto (nombre, descripcion, estado) values ('Shrimp - 16/20, Iqf, Shell On', 'Enterprise-wide tangible benchmark', true);
insert into cat_producto (nombre, descripcion, estado) values ('Instant Coffee', 'Assimilated motivating open system', false);
insert into cat_producto (nombre, descripcion, estado) values ('Pepper - Roasted Red', 'Advanced secondary leverage', true);
insert into cat_producto (nombre, descripcion, estado) values ('Bread - Flat Bread', 'Secured eco-centric infrastructure', false);
insert into cat_producto (nombre, descripcion, estado) values ('Yogurt - Strawberry, 175 Gr', 'Compatible asynchronous moderator', true);
insert into cat_producto (nombre, descripcion, estado) values ('Asparagus - Frozen', 'Fundamental coherent orchestration', false);
insert into cat_producto (nombre, descripcion, estado) values ('Hipnotiq Liquor', 'Grass-roots stable challenge', false);
insert into cat_producto (nombre, descripcion, estado) values ('Chocolate - Compound Coating', 'Ameliorated methodical monitoring', false);
insert into cat_producto (nombre, descripcion, estado) values ('Wine - Fume Blanc Fetzer', 'Adaptive demand-driven framework', true);
insert into cat_producto (nombre, descripcion, estado) values ('Oil - Coconut', 'Synchronised secondary knowledge user', false);
insert into cat_producto (nombre, descripcion, estado) values ('Bread - Wheat Baguette', 'Organized solution-oriented archive', true);
insert into cat_producto (nombre, descripcion, estado) values ('Bok Choy - Baby', 'Proactive 6th generation interface', false);
insert into cat_producto (nombre, descripcion, estado) values ('Napkin White', 'Customer-focused asymmetric framework', true);
insert into cat_producto (nombre, descripcion, estado) values ('Wine - Fat Bastard Merlot', 'Exclusive exuding contingency', false);
insert into cat_producto (nombre, descripcion, estado) values ('Bread - Malt', 'Profit-focused dynamic encoding', false);
insert into cat_producto (nombre, descripcion, estado) values ('Bread - Kimel Stick Poly', 'Persevering grid-enabled contingency', true);
insert into cat_producto (nombre, descripcion, estado) values ('Mussels - Frozen', 'Programmable homogeneous benchmark', true);
insert into cat_producto (nombre, descripcion, estado) values ('Doilies - 8, Paper', 'Self-enabling contextually-based contingency', true);
insert into cat_producto (nombre, descripcion, estado) values ('Flower - Commercial Bronze', 'Secured maximized service-desk', true);
insert into cat_producto (nombre, descripcion, estado) values ('Cheese - Gouda Smoked', 'Reduced well-modulated challenge', false);
insert into cat_producto (nombre, descripcion, estado) values ('Beef - Roasted, Cooked', 'Exclusive directional groupware', false);
insert into cat_producto (nombre, descripcion, estado) values ('Rice - Aborio', 'Public-key transitional encryption', false);
insert into cat_producto (nombre, descripcion, estado) values ('Sobe - Lizard Fuel', 'Persevering scalable functionalities', false);
insert into cat_producto (nombre, descripcion, estado) values ('Carbonated Water - White Grape', 'Visionary interactive website', true);
insert into cat_producto (nombre, descripcion, estado) values ('Wine - Puligny Montrachet A.', 'Public-key 24 hour groupware', true);
insert into cat_producto (nombre, descripcion, estado) values ('Wine - Magnotta - Pinot Gris Sr', 'Down-sized system-worthy productivity', true);
insert into cat_producto (nombre, descripcion, estado) values ('Walkers Special Old Whiskey', 'Centralized secondary forecast', true);
insert into cat_producto (nombre, descripcion, estado) values ('Pear - Asian', 'Centralized encompassing circuit', false);
insert into cat_producto (nombre, descripcion, estado) values ('Pepper - White, Ground', 'Polarised asymmetric emulation', true);
insert into cat_producto (nombre, descripcion, estado) values ('Shark - Loin', 'Fundamental homogeneous algorithm', true);
insert into cat_producto (nombre, descripcion, estado) values ('Pepper - Roasted Red', 'Focused neutral definition', false);
insert into cat_producto (nombre, descripcion, estado) values ('Pastry - Baked Scones - Mini', 'Focused zero defect benchmark', true);
insert into cat_producto (nombre, descripcion, estado) values ('Vodka - Hot, Lnferno', 'Triple-buffered fresh-thinking superstructure', true);
insert into cat_producto (nombre, descripcion, estado) values ('Soy Protein', 'Ergonomic stable process improvement', false);
insert into cat_producto (nombre, descripcion, estado) values ('Cheese - Feta', 'Streamlined asynchronous support', false);
insert into cat_producto (nombre, descripcion, estado) values ('Pop - Club Soda Can', 'Sharable explicit encoding', false);
insert into cat_producto (nombre, descripcion, estado) values ('Ecolab - Hand Soap Form Antibac', 'Organized composite focus group', false);
insert into cat_producto (nombre, descripcion, estado) values ('Yoplait Drink', 'Universal coherent budgetary management', false);
insert into cat_producto (nombre, descripcion, estado) values ('Cheese - Comte', 'Self-enabling directional interface', false);
insert into cat_producto (nombre, descripcion, estado) values ('Pastry - Apple Large', 'Grass-roots leading edge capacity', false);
insert into cat_producto (nombre, descripcion, estado) values ('Lamb - Whole, Frozen', 'Reactive zero administration concept', false);
insert into cat_producto (nombre, descripcion, estado) values ('Stock - Chicken, White', 'Switchable static artificial intelligence', false);
insert into cat_producto (nombre, descripcion, estado) values ('Juice - Apple, 1.36l', 'Phased 6th generation ability', false);
insert into cat_producto (nombre, descripcion, estado) values ('Whmis Spray Bottle Graduated', 'Organized logistical encryption', false);
insert into cat_producto (nombre, descripcion, estado) values ('Cheese - Wine', 'Stand-alone explicit infrastructure', true);
insert into cat_producto (nombre, descripcion, estado) values ('Hand Towel', 'Ameliorated systemic hub', false);
insert into cat_producto (nombre, descripcion, estado) values ('Beef - Striploin', 'Re-engineered demand-driven approach', false);
insert into cat_producto (nombre, descripcion, estado) values ('Potatoes - Instant, Mashed', 'Fully-configurable object-oriented instruction set', true);
insert into cat_producto (nombre, descripcion, estado) values ('Truffle Paste', 'Inverse systemic interface', true);
insert into cat_producto (nombre, descripcion, estado) values ('Muffin Mix - Carrot', 'Versatile client-server architecture', true);
insert into cat_producto (nombre, descripcion, estado) values ('Sugar - Crumb', 'Advanced asynchronous protocol', false);
insert into cat_producto (nombre, descripcion, estado) values ('Rum - Light, Captain Morgan', 'Face to face intangible matrices', false);
insert into cat_producto (nombre, descripcion, estado) values ('Tea - Herbal - 6 Asst', 'Reactive systematic model', false);
insert into cat_producto (nombre, descripcion, estado) values ('Bread - Italian Roll With Herbs', 'Sharable client-driven approach', true);
insert into cat_producto (nombre, descripcion, estado) values ('Mushroom - Shitake, Dry', 'Public-key local paradigm', false);
insert into cat_producto (nombre, descripcion, estado) values ('Island Oasis - Strawberry', 'Reverse-engineered attitude-oriented system engine', true);
insert into cat_producto (nombre, descripcion, estado) values ('Fish - Atlantic Salmon, Cold', 'Enhanced interactive internet solution', true);
insert into cat_producto (nombre, descripcion, estado) values ('Muffin Batt - Blueberry Passion', 'Persistent real-time installation', true);
insert into cat_producto (nombre, descripcion, estado) values ('Crawfish', 'Inverse impactful service-desk', false);
insert into cat_producto (nombre, descripcion, estado) values ('Flour - Buckwheat, Dark', 'Cross-group client-driven core', true);
insert into cat_producto (nombre, descripcion, estado) values ('Dates', 'Universal explicit portal', false);
insert into cat_producto (nombre, descripcion, estado) values ('Mix - Cocktail Ice Cream', 'Profound client-server process improvement', false);
insert into cat_producto (nombre, descripcion, estado) values ('Limes', 'Diverse context-sensitive approach', true);
insert into cat_producto (nombre, descripcion, estado) values ('Soup - Knorr, Chicken Noodle', 'Automated motivating system engine', true);
insert into cat_producto (nombre, descripcion, estado) values ('Pepper - Orange', 'Quality-focused content-based contingency', false);
insert into cat_producto (nombre, descripcion, estado) values ('Beans - Navy, Dry', 'Fundamental incremental application', false);
insert into cat_producto (nombre, descripcion, estado) values ('Sauce - Hp', 'Ergonomic client-driven customer loyalty', true);
insert into cat_producto (nombre, descripcion, estado) values ('Bread - White Epi Baguette', 'Reduced logistical hardware', false);
insert into cat_producto (nombre, descripcion, estado) values ('Island Oasis - Magarita Mix', 'Optional disintermediate system engine', false);
insert into cat_producto (nombre, descripcion, estado) values ('Beef - Tenderloin', 'Advanced needs-based circuit', true);
insert into cat_producto (nombre, descripcion, estado) values ('Knife Plastic - White', 'Face to face holistic structure', true);
insert into cat_producto (nombre, descripcion, estado) values ('Liqueur Banana, Ramazzotti', 'Synergistic zero tolerance initiative', true);
insert into cat_producto (nombre, descripcion, estado) values ('Praline Paste', 'Ergonomic modular forecast', true);
insert into cat_producto (nombre, descripcion, estado) values ('Pickles - Gherkins', 'Managed object-oriented matrices', false);
insert into cat_producto (nombre, descripcion, estado) values ('Skewers - Bamboo', 'Configurable coherent moratorium', true);
insert into cat_producto (nombre, descripcion, estado) values ('Sugar - Icing', 'Decentralized systemic solution', false);
insert into cat_producto (nombre, descripcion, estado) values ('Cheese - Fontina', 'Visionary user-facing array', false);
insert into cat_producto (nombre, descripcion, estado) values ('Cucumber - Pickling Ontario', 'Down-sized logistical forecast', false);
